import { useRef, useState } from "react";

import { createDashboardViewModel, createPosterModel, finalDashboard, formatFinalNumber, formatRaceCheckpoint, leaderRaceSummary, type RaceCheckpoint, type Standing } from "./final-dashboard-data";
import { getMobileStandingsRows, mobileNav, nextTabIndex, standingsDisclosureLabel } from "./final-dashboard-ui";

const tabs = ["group", "knockout", "overall"] as const;
type Tab = (typeof tabs)[number];
const raceMilestones = [73, 88, 98, 100, 101, 102] as const;

function TeamScore({ home, score, away }: { home: string; score: string; away: string }) {
  return <p className="font-display text-2xl font-extrabold tracking-[-.04em] text-[#291715] sm:text-3xl">{home} <span className="text-[#BD0015]">{score}</span> {away}</p>;
}

async function canvasBlob(canvas: HTMLCanvasElement) {
  return new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png"));
}

function RaceChart({ activeMatch, onCheckpointChange, race }: { activeMatch: number; onCheckpointChange: (match: number) => void; race: readonly RaceCheckpoint[] }) {
  const series = [
    ["q", "Q", "#BD0015"], ["sergio", "Sergio", "#2A398D"], ["tesoro", "Tesoro", "#3CAC3B"],
    ["sofi", "Sofi", "#97A5FF"], ["boris", "Boris", "#291715"], ["quique", "Quique Menjívar", "#5D3F3C"],
  ] as const;
  const point = (index: number, value: number) => `${20 + (index * 600) / (race.length - 1)},${220 - (value * 180) / 47}`;
  return <div className="overflow-x-auto rounded-[28px] bg-white p-5">
    <svg className="h-[280px] min-w-[620px] w-full" viewBox="0 0 640 260" role="group" aria-label="Carrera de eliminatorias: seis series acumuladas desde M73 hasta M104">
      {raceMilestones.map((match) => {
        const index = race.findIndex((checkpoint) => checkpoint.match === match);
        const x = 20 + (index * 600) / (race.length - 1);
        return <g key={match}><line stroke="rgba(41,23,21,.25)" strokeDasharray="4 5" x1={x} x2={x} y1="16" y2="220"/><text fill="#291715" fontSize="12" textAnchor="end" transform={`rotate(-48 ${x} 248)`} x={x} y="248">M{match}</text></g>;
      })}
      {series.map(([key, label, color]) => <polyline fill="none" key={key} points={race.map((checkpoint, index) => point(index, checkpoint.scores[key])).join(" ")} stroke={color} strokeLinecap="round" strokeLinejoin="round" strokeWidth={key === "q" ? 4 : 2.5}><title>{label}</title></polyline>)}
      {race.map((checkpoint, index) => {
        const x = 20 + (index * 600) / (race.length - 1);
        const y = 220 - (checkpoint.leaderPoints * 180) / 47;
        const detail = formatRaceCheckpoint(checkpoint);
        return <g aria-label={detail.ariaLabel} className="group cursor-pointer focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#BD0015]" key={checkpoint.match} onClick={() => onCheckpointChange(checkpoint.match)} onFocus={() => onCheckpointChange(checkpoint.match)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onCheckpointChange(checkpoint.match); } }} onMouseEnter={() => onCheckpointChange(checkpoint.match)} role="button" tabIndex={0}><circle cx={x} cy={y} fill="transparent" r="22"/><circle className="group-focus-visible:stroke-[#BD0015] group-focus-visible:[stroke-width:3]" cx={x} cy={y} fill={checkpoint.match === activeMatch ? "#FFF8F7" : "white"} r="5" stroke="#291715" strokeWidth="1.5"/><title>{detail.ariaLabel}</title></g>;
      })}
    </svg>
    <ul className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[#291715]" aria-label="Leyenda de la carrera">
      {series.map(([key, label, color]) => <li className="flex items-center gap-2" key={key}><span aria-hidden="true" className="size-3 rounded-full" style={{ backgroundColor: color }}/>{label}: {race.at(-1)?.scores[key]}</li>)}
    </ul>
  </div>;
}

export function FinalDashboard() {
  const [tab, setTab] = useState<Tab>("group");
  const [standingsExpanded, setStandingsExpanded] = useState(false);
  const [activeRaceMatch, setActiveRaceMatch] = useState(73);
  const [posterError, setPosterError] = useState("");
  const poster = useRef<HTMLDivElement>(null);
  const phase = finalDashboard.phases[tab];
  const posterModel = createPosterModel(finalDashboard);
  const viewModel = createDashboardViewModel(finalDashboard);
  const milestones = raceMilestones.map((match) => finalDashboard.knockoutRace.find((checkpoint) => checkpoint.match === match)!);
  const milestone = finalDashboard.knockoutRace.find((checkpoint) => checkpoint.match === activeRaceMatch) ?? milestones[0]!;
  const milestoneIndex = milestones.findIndex((checkpoint) => checkpoint.match === milestone.match);
  const raceDetail = formatRaceCheckpoint(milestone);
  const mobileRows = getMobileStandingsRows(phase.standings, standingsExpanded);

  async function downloadPoster() {
    if (!poster.current) return;
    setPosterError("");
    try {
      const { default: html2canvas } = await import("html2canvas");
      await document.fonts?.ready;
      const blob = await canvasBlob(await html2canvas(poster.current, { backgroundColor: "#FFF8F7", scale: 1 }));
      if (!blob) throw new Error("No se pudo crear el PNG.");
      const file = new File([blob], "quiniela-mundial-2026-resumen-final.png", { type: "image/png" });
      if (navigator.share && navigator.canShare?.({ files: [file] })) {
        try { await navigator.share({ files: [file], title: "Quiniela Mundial 2026" }); return; } catch { /* descargar como fallback */ }
      }
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = file.name;
      document.body.append(link);
      link.click();
      link.remove();
      window.setTimeout(() => URL.revokeObjectURL(url), 0);
    } catch (error) {
      setPosterError(error instanceof Error ? error.message : "No se pudo descargar el resumen.");
    }
  }

  return <div className="final-dashboard overflow-x-hidden bg-[#FFF8F7] text-[#291715]">
    <header className="sticky top-0 z-20 border-b border-[#E7BDB8] bg-[#FFF8F7]/95 backdrop-blur">
      <nav className="mx-auto flex h-[68px] max-w-[1400px] items-center justify-between gap-3 px-4 sm:px-6 lg:px-10" aria-label="Navegación principal">
        <a className="font-display text-lg font-extrabold tracking-[-.04em] text-[#2A398D]" href="#historia">Quiniela Mundial 2026</a>
        <div className="hidden items-center gap-4 text-sm font-semibold lg:flex">{mobileNav.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}</div>
        <button className="min-h-11 rounded-xl bg-[#BD0015] px-3 text-sm font-bold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2A398D]" onClick={downloadPoster} type="button">Descargar resumen</button>
      </nav>
      <nav className="flex min-h-11 gap-1 overflow-x-auto border-t border-[#E7BDB8] px-4 lg:hidden" aria-label="Secciones del archivo">{mobileNav.map((item) => <a className="inline-flex min-h-11 shrink-0 items-center px-3 text-sm font-semibold underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[#2A398D] focus-visible:underline" href={item.href} key={item.href}>{item.label}</a>)}</nav>
    </header>
    <main id="main-content">
      <section className="mx-auto grid min-h-[calc(100dvh-112px)] max-w-[1400px] items-center gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[7fr_5fr] lg:px-10 lg:py-14" id="historia">
        <div><p className="mb-5 text-sm font-bold text-[#BD0015]">Mundial 2026 | Archivo final · 19 de julio de 2026</p><h1 className="max-w-3xl font-display text-5xl font-black leading-[.92] tracking-[-.06em] text-[#2A398D] sm:text-6xl lg:text-7xl">La quiniela terminó. La historia quedó.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#5D3F3C] sm:text-lg">Q ganó las eliminatorias, Otto se quedó con los grupos y España levantó la copa después de una final que nadie clavó.</p><div className="mt-8 flex flex-wrap gap-3"><a className="inline-flex min-h-11 items-center rounded-xl bg-[#BD0015] px-5 font-bold text-white" href="#carrera">Ver cómo se decidió</a><button className="min-h-11 rounded-xl border border-[#2A398D] px-5 font-bold text-[#2A398D]" onClick={downloadPoster} type="button">Descargar resumen</button></div>{posterError && <p className="mt-3 text-sm font-semibold text-[#BD0015]" role="status">{posterError}</p>}</div>
        <div className="relative min-h-[330px] overflow-hidden rounded-[32px] border-2 border-[#2A398D] bg-[#2A398D] p-6 text-white" role="img" aria-label="Ilustración local de los tres campeonatos"><div className="absolute -right-16 -top-12 size-72 rounded-full border-[34px] border-[#97A5FF]"/><div className="relative grid h-full grid-cols-3 items-end gap-3"><Medal label="O" title={`${viewModel.groupChampion.name} · ${viewModel.groupChampion.points}`} color="bg-[#97A5FF]"/><Medal label="Q" title={`${viewModel.knockoutChampion.name} · ${viewModel.knockoutChampion.points}`} color="bg-[#BD0015]" large/><Medal label="ESP" title={posterModel.worldChampion} color="bg-[#3CAC3B]"/></div><p className="absolute bottom-5 right-6 text-sm font-bold">{viewModel.final.score} · {viewModel.final.extraTimeScore} TE</p></div>
      </section>
      <section className="border-y border-[#E7BDB8] bg-white"><div className="mx-auto grid max-w-[1400px] grid-cols-2 divide-x divide-y divide-[#E7BDB8] px-4 sm:grid-cols-5 sm:divide-y-0 sm:px-6 lg:px-10">{[[viewModel.meta.participants, "participantes"], [viewModel.meta.matches, "partidos"], [formatFinalNumber(viewModel.meta.predictions), "predicciones públicas"], [`${viewModel.meta.participation}%`, "de participación"], [viewModel.leaderChanges, "cambios de líder"]].map(([value, label]) => <div className="p-5 sm:p-6" key={label}><p className="font-display text-3xl font-black tabular-nums text-[#2A398D]">{value}</p><p className="mt-1 text-xs font-semibold text-[#5D3F3C]">{label}</p></div>)}</div></section>
      <section className="mx-auto max-w-[1400px] px-4 py-16 sm:px-6 lg:px-10 lg:py-24" id="campeones"><h2 className="font-display text-4xl font-black tracking-[-.05em] text-[#2A398D] sm:text-5xl">Hubo dos campeonatos. Los dos llegaron apretados.</h2><div className="mt-10 grid gap-5 lg:grid-cols-2"><Champion champion={viewModel.groupChampion} detail={`${viewModel.groupRunnerUp.name} terminó segundo con ${viewModel.groupRunnerUp.points}.`} tone="blue" title="Campeón de grupos"/><Champion champion={viewModel.knockoutChampion} detail={`${viewModel.knockoutRunnerUps.map((row) => row.name).join(" y ")} compartieron el segundo lugar con ${viewModel.knockoutRunnerUps[0]?.points}.`} tone="red" title="Campeona de eliminatorias"/></div></section>
      <section className="bg-[#2A398D] py-16 text-white lg:py-24" id="carrera"><div className="mx-auto max-w-[1400px] px-4 sm:px-6 lg:px-10"><h2 className="font-display text-4xl font-black tracking-[-.05em] sm:text-5xl">{viewModel.leaderChanges} cambios de líder en {finalDashboard.knockoutRace.length} partidos</h2><p className="mt-4 max-w-3xl text-white/85">Las seis series muestran los puntos acumulados reales de eliminatorias. M103 y M104 mantienen el liderato de Q.</p><div className="mt-8 grid gap-6 lg:grid-cols-[8fr_4fr]"><RaceChart activeMatch={milestone.match} onCheckpointChange={setActiveRaceMatch} race={finalDashboard.knockoutRace}/><div aria-live="polite" className="rounded-[28px] bg-white p-5 text-[#291715]"><p className="font-display text-xl font-black">{raceDetail.title}</p><p className="mt-2 text-sm leading-6 text-[#5D3F3C]">{raceDetail.description}</p><div className="mt-6 flex gap-2"><button className="min-h-11 rounded-xl border border-[#2A398D] px-3 font-semibold" onClick={() => setActiveRaceMatch(milestones[(milestoneIndex + milestones.length - 1) % milestones.length]!.match)} type="button">Anterior</button><button className="min-h-11 rounded-xl bg-[#BD0015] px-3 font-semibold text-white" onClick={() => setActiveRaceMatch(milestones[(milestoneIndex + 1) % milestones.length]!.match)} type="button">Siguiente</button></div></div></div><p className="mt-6 max-w-4xl rounded-2xl border border-white/25 p-4 text-sm leading-6">{leaderRaceSummary}</p></div></section>
      <section className="mx-auto max-w-[1400px] px-4 py-16 sm:px-6 lg:px-10 lg:py-24"><h2 className="font-display text-4xl font-black tracking-[-.05em] text-[#BD0015] sm:text-5xl">{viewModel.qSummary.exacts} marcadores exactos para ganar</h2><ol className="mt-10 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{finalDashboard.qPath.map(([match, stage, home, away, score]) => <li className="rounded-2xl border border-[#E7BDB8] bg-white p-4" key={match}><p className="text-xs font-bold text-[#BD0015]">M{match} · {stage}{match === 102 ? " · liderato definitivo" : ""}</p><TeamScore away={away} home={home} score={score}/><p className="mt-2 text-sm text-[#5D3F3C]">+3 puntos</p></li>)}</ol><p className="mt-6 text-sm text-[#5D3F3C]"><strong>{viewModel.qSummary.points} puntos · {viewModel.qSummary.exacts} exactos · {viewModel.qSummary.hits} resultados acertados en {viewModel.qSummary.predictions} predicciones · {viewModel.qSummary.precision}% de precisión.</strong> Q no sumó en M103 ni M104: la ventaja ya estaba decidida.</p></section>
      <section className="border-y border-[#E7BDB8] bg-white py-16 lg:py-24" id="momentos"><div className="mx-auto max-w-[1400px] px-4 sm:px-6 lg:px-10"><h2 className="font-display text-4xl font-black tracking-[-.05em] text-[#2A398D]">Lo que todos celebramos y lo que nadie vio venir</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{finalDashboard.moments.map((moment) => <article className={`rounded-[28px] border p-5 ${moment.tone === "celebración" ? "border-[#3CAC3B] bg-[#eff9ef]" : "border-[#E7BDB8] bg-[#FFE9E6]"}`} key={moment.score}><p className="text-xs font-bold uppercase tracking-wide">{moment.tone}</p><h3 className="mt-5 font-display text-2xl font-black text-[#2A398D]">{moment.score}</h3><p className="mt-2 font-semibold">{moment.title}</p><p className="mt-3 text-sm leading-6 text-[#5D3F3C]">{moment.detail}</p></article>)}</div></div></section>
      <section className="mx-auto max-w-[1400px] px-4 py-16 sm:px-6 lg:px-10 lg:py-24" id="reconocimientos"><p className="text-sm font-bold text-[#BD0015]">Lectura editorial · no es competencia oficial</p><h2 className="font-display text-4xl font-black tracking-[-.05em] text-[#2A398D] sm:text-5xl">Lo que cada quien hizo mejor</h2><p className="mt-4 max-w-3xl text-[#5D3F3C]">Reconocimientos calculados sobre los {viewModel.meta.matches} partidos. No forman una tabla oficial.</p><div className="mt-8 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><article className="rounded-[28px] bg-[#2A398D] p-7 text-white"><p className="text-sm font-bold">{viewModel.awards[0]?.[1]}</p><div className="mt-12 flex items-end justify-between gap-4"><h3 className="font-display text-6xl font-black tracking-[-.06em]">{viewModel.awards[0]?.[0]}</h3><p className="font-display text-5xl font-black tabular-nums">{viewModel.awards[0]?.[2]}</p></div><p className="mt-4 text-sm text-white/80">puntos en la lectura editorial</p></article><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">{viewModel.awards.slice(1, 3).map(([name, label, value]) => <article className="rounded-[28px] border border-[#E7BDB8] bg-white p-5" key={`${name}-${label}`}><p className="text-sm font-bold text-[#BD0015]">{label}</p><p className="mt-7 font-display text-4xl font-black text-[#2A398D]">{name}</p><p className="mt-1 text-xl font-bold tabular-nums">{value}</p></article>)}</div></div><ul className="mt-4 flex flex-wrap gap-3 border-y border-[#E7BDB8] py-4" aria-label="Otros reconocimientos editoriales">{viewModel.awards.slice(3).map(([name, label, value]) => <li className="min-w-[150px] grow border-l-4 border-[#97A5FF] pl-3" key={`${name}-${label}`}><p className="font-bold">{name} · {value}</p><p className="text-sm text-[#5D3F3C]">{label}</p></li>)}</ul></section>
      <section className="bg-[#2A398D] py-16 text-white lg:py-24" id="noche-final"><div className="mx-auto grid max-w-[1400px] gap-8 px-4 sm:px-6 lg:grid-cols-2 lg:px-10"><div><h2 className="font-display text-4xl font-black tracking-[-.05em] sm:text-5xl">La final que nadie clavó</h2><p className="mt-5 max-w-xl leading-7 text-white/85">España y Argentina terminaron {viewModel.final.score} en los 90 minutos: ese fue el marcador que puntuó. España ganó {viewModel.final.extraTimeScore} en tiempo extra y levantó la copa.</p><p className="mt-4 font-bold">La final decidió al campeón mundial, pero no movió el podio de la quiniela.</p></div><div className="rounded-[28px] bg-white p-6 text-[#291715]"><p className="font-display text-4xl font-black">{viewModel.final.score} <span className="text-base font-bold">a los 90 minutos</span></p><p className="mt-3 text-lg font-bold">España {viewModel.final.extraTimeScore} Argentina en tiempo extra · España campeona</p><p className="mt-8 text-sm">{viewModel.final.predictions} pronósticos · {viewModel.final.exacts} exactos · {viewModel.final.drawHits} aciertos de empate</p><div className="mt-4 grid grid-cols-[8fr_5fr_8fr] gap-1 text-center text-xs font-bold"><span className="rounded bg-[#97A5FF] p-3">{viewModel.final.distribution[0]} España</span><span className="rounded bg-[#FFE9E6] p-3">{viewModel.final.distribution[1]} empate</span><span className="rounded bg-[#BD0015] p-3 text-white">{viewModel.final.distribution[2]} Argentina</span></div></div></div></section>
      <section className="mx-auto max-w-[1400px] px-4 py-16 sm:px-6 lg:px-10 lg:py-24" id="tabla-final"><h2 className="font-display text-4xl font-black tracking-[-.05em] text-[#2A398D] sm:text-5xl">Así terminaron las dos competencias</h2><div className="mt-8 flex flex-wrap gap-2" role="tablist" aria-label="Tablas finales">{tabs.map((id, index) => <button aria-controls={`panel-${id}`} aria-selected={tab === id} className={`min-h-11 rounded-full px-4 text-sm font-bold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2A398D] ${tab === id ? "bg-[#2A398D] text-white" : "border border-[#2A398D] text-[#2A398D]"}`} id={`tab-${id}`} key={id} onClick={() => { setTab(id); setStandingsExpanded(false); }} onKeyDown={(event) => { const next = nextTabIndex(index, event.key, tabs.length); if (next !== index) { event.preventDefault(); setTab(tabs[next]!); setStandingsExpanded(false); document.getElementById(`tab-${tabs[next]}`)?.focus(); } }} role="tab" type="button">{finalDashboard.phases[id].label}{id !== "overall" ? " · oficial" : ""}</button>)}</div><div aria-labelledby={`tab-${tab}`} className="mt-4" id={`panel-${tab}`} role="tabpanel"><p className="mb-4 text-sm text-[#5D3F3C]">{phase.matchCount} partidos · {phase.predictionCount.toLocaleString("es-ES")} predicciones{phase.official ? " · tabla oficial." : " · La suma de grupos y eliminatorias es una lectura editorial. No fue una tercera competencia oficial."}</p><StandingsTable mobileRows={mobileRows} onToggle={() => setStandingsExpanded((expanded) => !expanded)} rows={phase.standings} showAll={standingsExpanded}/></div></section>
      <section className="border-t border-[#E7BDB8] bg-white py-16"><div className="mx-auto max-w-[1400px] px-4 sm:px-6 lg:px-10"><h2 className="font-display text-3xl font-black text-[#2A398D]">Cómo se contaron los puntos</h2><p className="mt-4 max-w-4xl leading-7 text-[#5D3F3C]">Cada marcador exacto valió 3 puntos. Acertar el resultado y los goles de un equipo valió 2. Acertar el resultado o los goles de un equipo valió 1. En eliminatorias se usó el marcador al terminar los 90 minutos.</p></div></section>
    </main>
    <div aria-hidden="true" className="fixed left-[-10000px] top-0"><div className="flex h-[1920px] w-[1080px] flex-col bg-[#FFF8F7] p-20 text-[#291715]" ref={poster}><p className="font-display text-5xl font-black text-[#2A398D]">Quiniela Mundial 2026</p><div className="mt-20 rounded-[48px] bg-[#2A398D] p-16 text-white"><p className="font-display text-9xl font-black">{posterModel.knockoutChampion.name} · {posterModel.knockoutChampion.points}</p><p className="mt-5 text-4xl">Campeona de eliminatorias</p><p className="mt-20 font-display text-7xl font-black">{posterModel.groupChampion.name} · {posterModel.groupChampion.points}</p><p className="mt-4 text-3xl">Campeón de grupos</p><p className="mt-20 font-display text-7xl font-black">{posterModel.worldChampion} campeona</p></div><p className="mt-12 font-display text-5xl font-black">{posterModel.meta.participants} participantes · {posterModel.meta.matches} partidos · {formatFinalNumber(posterModel.meta.predictions)} predicciones</p><p className="mt-10 text-4xl">{posterModel.leaderChanges} cambios de líder · Final {posterModel.finalScore} a los 90' · {posterModel.extraTimeScore} TE</p><div className="mt-10 grid gap-4">{posterModel.moments.map((moment) => <p className="rounded-2xl border border-[#E7BDB8] p-4 text-2xl" key={moment.score}><strong>{moment.score}</strong> · {moment.detail}</p>)}</div><p className="mt-auto text-2xl font-bold">{posterModel.signature}</p></div></div>
  </div>;
}

function Medal({ label, title, color, large = false }: { label: string; title: string; color: string; large?: boolean }) { return <div className={`relative grid aspect-square place-items-center rounded-full border-8 border-white/80 ${color} ${large ? "scale-110" : ""}`}><span className="font-display text-4xl font-black">{label}</span><span className="absolute -bottom-8 whitespace-nowrap text-xs font-bold">{title}</span></div>; }
function Champion({ champion, detail, tone, title }: { champion: { name: string; points: number }; detail: string; tone: "blue" | "red"; title: string }) { return <article className={`rounded-[28px] p-7 text-white ${tone === "red" ? "bg-[#BD0015]" : "bg-[#2A398D]"}`}><p className="text-sm font-bold">{title}</p><div className="mt-10 flex items-end justify-between"><h3 className="font-display text-5xl font-black tracking-[-.05em]">{champion.name}</h3><p className="font-display text-6xl font-black tabular-nums">{champion.points}</p></div><p className="mt-4 text-sm">{detail}</p></article>; }
function StandingsTable({ mobileRows, onToggle, rows, showAll }: { mobileRows: readonly Standing[]; onToggle: () => void; rows: readonly Standing[]; showAll: boolean }) { return <><div className="rounded-2xl border border-[#E7BDB8] bg-white md:hidden">{mobileRows.map((row) => <div className="grid grid-cols-[2.5rem_1fr_auto] gap-2 border-b border-[#E7BDB8]/70 p-3 last:border-0" key={row.name}><strong>{row.rank}</strong><div><p className="font-semibold">{row.name}</p><p className="text-xs text-[#5D3F3C]">{row.exacts} exactos · {row.hits} aciertos · {row.precision.toFixed(1)}%</p></div><strong className="text-right">{row.points}<span className="block text-xs text-[#5D3F3C]">pts</span></strong></div>)}<button aria-expanded={showAll} className="min-h-11 w-full border-t border-[#E7BDB8] px-3 font-bold text-[#2A398D] focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[#2A398D]" onClick={onToggle} type="button">{standingsDisclosureLabel(showAll, rows.length)}</button></div><div className="hidden overflow-x-auto rounded-2xl border border-[#E7BDB8] bg-white md:block"><table className="w-full min-w-[700px] border-collapse text-sm tabular-nums"><caption className="sr-only">Tabla completa de {rows.length} participantes</caption><thead className="bg-[#FFF8F7]"><tr className="border-b border-[#E7BDB8] text-left text-xs text-[#5D3F3C]"><th className="p-3" scope="col">Pos.</th><th className="p-3" scope="col">Participante</th><th className="p-3 text-right" scope="col">Pts</th><th className="p-3 text-right" scope="col">Pred.</th><th className="p-3 text-right" scope="col">Exactos</th><th className="p-3 text-right" scope="col">Aciertos</th><th className="p-3 text-right" scope="col">Precisión</th></tr></thead><tbody>{rows.map((row) => <tr className="border-b border-[#E7BDB8]/70 last:border-0" key={row.name}><th className="p-3 text-left font-bold" scope="row">{row.rank}</th><td className="p-3 font-semibold">{row.name}</td><td className="p-3 text-right font-bold">{row.points}</td><td className="p-3 text-right">{row.predictions}</td><td className="p-3 text-right">{row.exacts}</td><td className="p-3 text-right">{row.hits}</td><td className="p-3 text-right">{row.precision.toFixed(1)}%</td></tr>)}</tbody></table></div></>; }
