import type { CalendarMatch } from "./calendar-groups";

const teams = {
  RSA: { code: "RSA", flagEmoji: "🇿🇦", groupCode: "A", name: "Sudáfrica", worldRanking: 59 },
  CAN: { code: "CAN", flagEmoji: "🇨🇦", groupCode: "B", name: "Canadá", worldRanking: 30 },
  GER: { code: "GER", flagEmoji: "🇩🇪", groupCode: "E", name: "Alemania", worldRanking: 9 },
  PAR: { code: "PAR", flagEmoji: "🇵🇾", groupCode: "D", name: "Paraguay", worldRanking: 48 },
  NED: { code: "NED", flagEmoji: "🇳🇱", groupCode: "F", name: "Países Bajos", worldRanking: 7 },
  MAR: { code: "MAR", flagEmoji: "🇲🇦", groupCode: "C", name: "Marruecos", worldRanking: 12 },
  BRA: { code: "BRA", flagEmoji: "🇧🇷", groupCode: "C", name: "Brasil", worldRanking: 5 },
  JPN: { code: "JPN", flagEmoji: "🇯🇵", groupCode: "F", name: "Japón", worldRanking: 18 },
  FRA: { code: "FRA", flagEmoji: "🇫🇷", groupCode: "I", name: "Francia", worldRanking: 2 },
  SWE: { code: "SWE", flagEmoji: "🇸🇪", groupCode: "G", name: "Suecia", worldRanking: 28 },
  CIV: { code: "CIV", flagEmoji: "🇨🇮", groupCode: "E", name: "Costa de Marfil", worldRanking: 46 },
  NOR: { code: "NOR", flagEmoji: "🇳🇴", groupCode: "I", name: "Noruega", worldRanking: 33 },
  MEX: { code: "MEX", flagEmoji: "🇲🇽", groupCode: "A", name: "México", worldRanking: 14 },
  ECU: { code: "ECU", flagEmoji: "🇪🇨", groupCode: "H", name: "Ecuador", worldRanking: 24 },
  ENG: { code: "ENG", flagEmoji: "🏴", groupCode: "L", name: "Inglaterra", worldRanking: 4 },
  COD: { code: "COD", flagEmoji: "🇨🇩", groupCode: "J", name: "RD Congo", worldRanking: 60 },
  USA: { code: "USA", flagEmoji: "🇺🇸", groupCode: "D", name: "Estados Unidos", worldRanking: 16 },
  BIH: { code: "BIH", flagEmoji: "🇧🇦", groupCode: "B", name: "Bosnia", worldRanking: 71 },
  BEL: { code: "BEL", flagEmoji: "🇧🇪", groupCode: "G", name: "Bélgica", worldRanking: 8 },
  SEN: { code: "SEN", flagEmoji: "🇸🇳", groupCode: "A", name: "Senegal", worldRanking: 17 },
  POR: { code: "POR", flagEmoji: "🇵🇹", groupCode: "K", name: "Portugal", worldRanking: 6 },
  CRO: { code: "CRO", flagEmoji: "🇭🇷", groupCode: "L", name: "Croacia", worldRanking: 10 },
  ESP: { code: "ESP", flagEmoji: "🇪🇸", groupCode: "H", name: "España", worldRanking: 3 },
  AUT: { code: "AUT", flagEmoji: "🇦🇹", groupCode: "J", name: "Austria", worldRanking: 22 },
  SUI: { code: "SUI", flagEmoji: "🇨🇭", groupCode: "B", name: "Suiza", worldRanking: 19 },
  ALG: { code: "ALG", flagEmoji: "🇩🇿", groupCode: "E", name: "Argelia", worldRanking: 37 },
  ARG: { code: "ARG", flagEmoji: "🇦🇷", groupCode: "J", name: "Argentina", worldRanking: 1 },
  CPV: { code: "CPV", flagEmoji: "🇨🇻", groupCode: "H", name: "Cabo Verde", worldRanking: 65 },
  COL: { code: "COL", flagEmoji: "🇨🇴", groupCode: "K", name: "Colombia", worldRanking: 13 },
  GHA: { code: "GHA", flagEmoji: "🇬🇭", groupCode: "D", name: "Ghana", worldRanking: 69 },
  AUS: { code: "AUS", flagEmoji: "🇦🇺", groupCode: "D", name: "Australia", worldRanking: 26 },
  EGY: { code: "EGY", flagEmoji: "🇪🇬", groupCode: "G", name: "Egipto", worldRanking: 34 },
};

const fixtures = [
  [73, "RSA", "CAN", "finished", 0, 1],
  [74, "GER", "PAR", "scheduled"],
  [75, "NED", "MAR", "scheduled"],
  [76, "BRA", "JPN", "scheduled"],
  [77, "FRA", "SWE", "scheduled"],
  [78, "CIV", "NOR", "scheduled"],
  [79, "MEX", "ECU", "scheduled"],
  [80, "ENG", "COD", "scheduled"],
  [81, "USA", "BIH", "scheduled"],
  [82, "BEL", "SEN", "scheduled"],
  [83, "POR", "CRO", "scheduled"],
  [84, "ESP", "AUT", "scheduled"],
  [85, "SUI", "ALG", "scheduled"],
  [86, "ARG", "CPV", "scheduled"],
  [87, "COL", "GHA", "scheduled"],
  [88, "AUS", "EGY", "scheduled"],
] as const;

export function getDevCalendarPreviewMatches(): CalendarMatch[] {
  return fixtures.map(([matchNumber, homeCode, awayCode, status, homeScore, awayScore], index) => ({
    awayScore,
    awayTeam: { id: awayCode, ...teams[awayCode] },
    groupCode: null,
    homeScore,
    homeTeam: { id: homeCode, ...teams[homeCode] },
    kickoffAt: Date.UTC(2026, 5, 28 + Math.floor(index / 3), 19, 0),
    matchId: `dev-${matchNumber}`,
    matchNumber,
    stageLabel: "16avos",
    status,
    venue: "Preview local",
  }));
}
